### ISSUE TITLE
Web page for rapid image quality checking

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#1]
As a: ManualEvaluator
I want to: rapidly evaluate the quality of algorithm results,
so that: problems can be found and results published accurately

## Detailed Description

A lightweight web service that can be used to quickly rate 2D snapshots of images should be created for the purpose of rapid evaluation of 1000's of image.

### Tasks to be completed 

 - [x] Add node install instructions to setup
 - [x] Turn available_putamen_files_to_csv.ipynb into a python script
 - [x] Create set of instructions to configure and run the web tool
 - [x] Use slicer to inspect the 'bad' files.
 - [x] Create a Front-End that shows an image with 3 buttons: Good, Bad, and Save Progress
 - [x] Use node.js to handle HTTP Requests from button presses
 - [x] Use the web tool to identify 6000+ Putamen images as good or bad

### Acceptance Criteria

 - [x] A set of at least 1000 images needs to be reviewed in less than 3 hours time.
 - [x] A report must be generated that lists captures the manual evaluations in a single "csv or similar" file
 - [x] A set of instructions for how to configure and run the web tool must be written and submitted as part of this repository.
 - [x] All web code must be submitted to this git repository

**Comment by abpwrs** [comment]
@chasejohnson3 Is there more work associated with this issue or can it be closed?

**Comment by chasejohnson3** [comment]
All files flagged as potentially bad have been individually inspected in Slicer, and the results were saved in manually_evaluated_identified_putamen.csv.  This issue can now be closed.
