### ISSUE TITLE
Distribute Human Brain Data

### ISSUE THREAD

**Issue by chasejohnson3** [BRAINSia/SINAPSE#12]
As a: Developer
I want to: have access to human brain and mini pig brain data,
so that: Alex and I can begin the process of creating model to be applied to a mini pig based on results of human brains

## Detailed Description

Alex and I need access to and a location to retrieve the data.  This will require us knowing how to find the data and having access to it.

### Tasks to be completed 

 - [ ] Data distributed to Alex and Chase

 - [ ] Alex and Chase are given access/privileges to use the data

### Acceptance Criteria

 - [ ] Alex and Chase can get to and use the data.
