### ISSUE TITLE
Replace git-submodule with BRAINSia/NiftyNet fork

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#16]
# User Story
As software engineers,
@chasejohnson3 and @abpwrs will need a separate fork of NifTK/NiftyNet,
so that we can develop our landmark detection application.

## Detailed Description
Update the BRAINSia/NiftyNet fork and create a branch for our landmark detection.

### Tasks to be completed 

 - [x] Update BRAINSia/NiftyNet to be the same as NifTK/NiftyNet
 - [x] Create a new branch for landmark detection

### Acceptance Criteria
 - [x] @chasejohnson3 and @abpwrs must be able to commit and push to this new landmark branch of BRAINSia/NiftyNet

**Comment by abpwrs** [comment]
BRAINSia/NiftyNet/dev is now up to date.    
There is now a [landmark_app_20190405](https://github.com/BRAINSia/NiftyNet/tree/landmark_app_20190405) branch to develop our feature on
