### ISSUE TITLE
NiftyNet Notes

### ISSUE THREAD

**Issue by chasejohnson3** [BRAINSia/SINAPSE#17]
Take line-by-line notes on the application.py files of NiftyNet and add the notes to our forked version of NiftyNet.

# User Story

As a `Software Engineer trying to make my first NiftyNet model`,
I want `to understand the source code of NiftyNet`
so that `I can use NiftyNet to create a new type of deep learning application (landmark identification)`

### Tasks to be completed 

 - [ ] Go line by line through the _application.py files of NiftyNet's source code and take notes for usage and understanding
 - [ ] Create diagrams to illustrate associations between files and classes in NiftyNet

### Acceptance Criteria
 - [ ] We have enough understanding of NiftyNet to create our own application for NiftyNet

**Comment by abpwrs** [comment]
@ArjitJ These notes may or may not be helpful to you, but as you learn more it'd be great if you would add your notes here as well:    
https://github.com/BRAINSia/NiftyNet/wiki/docs
