### ISSUE TITLE
Improve Sphinx HTML report generation

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#18]
# User Story

As a `SoftwareEngineer`
I want `to have a web page that provides documentation for all python code`
so that `finding, understanding, and reusing previously developed code is convenient.`

## Detailed Description
The sphinx documentation tool should provide an HTML based report that includes auto-extracted information from the inline documents for each function/class and allows for rapid indexed identification.

### Tasks to be completed 

 - [X ] Instruement code
 - [ ] write scripts and documentation for how to run sphix to generate the hmtl reports
 - [ ] improve the html reports so that they look nice.

### Acceptance Criteria
 - [ ] A new developer should be able to read the README.md file for the Autoworkup directory and understand how to install and run sphinx to generate the indexed report.
 - [ ] A new developer should be able to start a web browser and view the sphinx documentation.
 - [ ] A new developer writing python code should be able to generate new docstrings and re-run sphinx to have their documentation included in the documentation report.
