### ISSUE TITLE
IIAI User-Manual Review

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#20]
Alex and Chase,

The following documentation is intended for getting people started in the deep learning laboratory.  Would each of you checkout this repo, read this document and make a pull request regarding necessary changes?

https://github.uiowa.edu/IIAI/DeepLearningLab4622SC/blob/master/User_Manual_IIAI_Lab/IIAI_Manual.md

# User Story

As `SoftwareEngineer new to the IIAI resources`,
I want `to understand the IIAI resources`
so that `I can quickly make use of the IIAI resources for research`

### Tasks to be completed 

 - [x] Chase Read and modify to improve clarity and add missing content
 - [x] Alex Read and modify to improve clarity and add missing content

### Acceptance Criteria
 - [x] A pull request made to the main repository with proposed changes
 - [x] PR reviewed and accepted.

**Comment by abpwrs** [comment]
First PR has been submitted.       
https://github.uiowa.edu/IIAI/DeepLearningLab4622SC/pull/9      
I will finish reviewing this tomorrow and add another PR.

**Comment by chasejohnson3** [comment]
Second PR has been submitted.
https://github.uiowa.edu/IIAI/DeepLearningLab4622SC/pull/11
