### ISSUE TITLE
NiftyNet LandmarkApplication

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#21]
# User Story
As AlgorithmDev,
I want a NiftyNet landmark detection interface
so that I can quickly develop landmark detection networks

## Detailed Description

Add a landmark detection application to the contrib folder of [BRAINSia/NiftyNet](https://github.com/BRAINSia/NiftyNet). This application should be extendable so that we can write our own landmark detection networks that use this. For more information on how the NiftyNet application works look at the results of #17.

### Tasks to be completed 

 - [x] Create a class [LandmarkApplication](https://github.com/BRAINSia/NiftyNet/blob/landmark_app_20190405/niftynet/contrib/landmark_application/landmark_application.py) that extends NiftyNet's BaseApplication class.
 - [ ] Add the generic functionalities of a landmark detection network (NEED MORE ISSUES TO FLUSH THIS OUT)
- [ ] Develop tests to ensure that our application behaves correctly and does not introduce breaking changes to NiftyNet

### Acceptance Criteria

 - [ ] Tests must be written that cover our code with at least a coverage of 70-80%
 - [ ] All existing NiftyNet test must pass
 - [ ] LandmarkApplication must be shown to work for landmark identification of eyes
 - [ ] Documentation of our new application must be written to work with existing NiftyNet docs
