### ISSUE TITLE
Compute HPC inter pupillary distance measures

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#22]
# User Story
As `Data analyst`,
I want `investigate relationships with interpupilary distance (IPD)`
so that `understand markers of intelligence related to IPD`

## Detailed Description

This is a followup to   #13 

We need a CSV file created with each row representing one scan session.  From the list of FCSV files, compute the distance between the LE and RE landmark points.

```csv
PROJECT, SUBJECT,SESSION,IPD
20190122_HCP_base_Results,149539,149539_hcpy1,51.818914582830025
```

### Tasks to be completed <!-- list anticipated work tasks needed, perhaps not complete

 - [ ] modify the python script https://github.com/BRAINSia/BRAINSTools/blob/master/BRAINSConstellationDetector/landmarkStatistics/computeIPD.py as needed
 - [ ] make list of all fcsv files to analyze
 - [ ] make csv file

### Acceptance Criteria
 - [ ] CSV file created and privately sent to hans-johnson@uiowa.edu

**Comment by KKnoernschild** [comment]
[SubjectIPDs.txt](https://github.com/BRAINSia/SINAPSE/files/3095165/SubjectIPDs.txt)

**Comment by KKnoernschild** [comment]
saved as txt so I could drop the file here. have a separate csv copy of the same name saved as well

**Comment by KKnoernschild** [comment]
need to add project, subject to file
