### ISSUE TITLE
Compute ABCD IPD measures

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#26]
# User Story
As `Data analyst`,
I want `investigate relationships with interpupilary distance (IPD) in the ABCD project`
so that `understand markers of intelligence related to IPD`

## Detailed Description

This is a followup to   #13 & #22

We need a CSV file created with each row representing one scan session.  From the list of FCSV files, compute the distance between the LE and RE landmark points.

```
find /Shared/ABCDchallenge/20190114_ABCD_base_Results/ABCDchallenge -name "BCD_ACPC_Landmarks.fcsv"
```

```csv
PROJECT, SUBJECT,SESSION,IPD
ABCDchallenge,NDARINVB8N5TFHV,NDARINVB8N5TFHV_baselineYear1Arm1,75.1231

```

### Tasks to be completed <!-- list anticipated work tasks needed, perhaps not complete

 - [ ] modify the python script https://github.com/BRAINSia/BRAINSTools/blob/master/BRAINSConstellationDetector/landmarkStatistics/computeIPD.py as needed
 - [ ] make list of all fcsv files to analyze
 - [ ] make csv file

### Acceptance Criteria
 - [ ] CSV file created and privately sent to hans-johnson@uiowa.edu

**Comment by hjmjohnson** [comment]
Email sent to Aaron on 20190419.
