### ISSUE TITLE
Re-run HCP data in BAW

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#27]
# User Story

As `DataCurator`,
I want `correctly registered data with proper eye locations`
so that `standard analysis can be performed without caveats`

## Detailed Description
Re-rerun BAW on all HCP data

### Tasks to be completed 

 - [ ] Figure out easy way to incorporate manually fixed FCSV files into process
 - [ ] Re-write csv data driver files for BAW
 - [ ] Reprocess all data with both T1's and T2's

### Acceptance Criteria

 - [ ] ICV measures from HCP data can be computed easily.
 - [ ] Verify that both T1 and T2 images are used
 - [ ] A testable behavior that must be accepted by appropriate stakeholder

### Appendix
related to #15

**Comment by hjmjohnson** [comment]
No longer relevant.
