### ISSUE TITLE
Move PREDICT-HD data to public location

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#28]
# User Story

As `DataCurator`,
I want `to make PREDICT-HD data widely acceptable`
so that `maximum value can be extracted from the data`

## Detailed Description

Daniel Miller is supportive of sharing data anywhere to maximize utilitiy.  DBGAP ID’s subject id,  standard scanid  throughout.

> NIH Data archive:  
> OpenNeuro. 

All Scan Dates need to be to —  rounded to date 15th of the month.  <—

Deface all T1 & T2 PD, FLAIR data.

——>  DWI, T2, PD, T1, FLARE,  T1rho, REST.    
PRE00[0-3] <— Roland will determine if the consents allow sharing.

4030 image sessions. 

### Tasks to be completed 

 - [ ] Ressurrect defacing algorithm
 - [ ] Round dates to 15th of months
 - [ ] Create data sets in BIDS format

### Acceptance Criteria

 - [ ] All data categorized
 - [ ] OpenNeuro Account created
 - [ ] Journal article written

**Comment by hjmjohnson** [comment]
```/Shared/paulsen/Experiments/20170820_DEFACE_PREDICT```

**Comment by hjmjohnson** [comment]
```
/Shared/johnsonhj/Binaries/20190513/Linux/NEP-11  <-- Broken binaries that do not yet have BIDS structure encoded.

## Alex updates to derived data outputs for NIPYPE data sinks
https://github.com/BRAINSia/BRAINSTools/tree/bids
```
