### ISSUE TITLE
Fiducial Finder Initial Steps

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#30]
# User Story

As an `AlgorithmDev `,
I want `understand the current field of landmark identification from deep learning methods`
so that `anatomical landmarks may be identified `

## Detailed Description

Survey literature to identify potential landmark identification strategies.

### Tasks to be completed

 - [ ] Survey different approaches to deep learning
 - [ ] Provide a proposal for initial testing (what will be tested, how will it be evaluated)
 - [ ] Provide small scale prototype

### Acceptance Criteria
 - [X] Create a wiki page to report on the literature findings (https://github.com/BRAINSia/SINAPSE/wiki/Fiducial-Finder)
 - [ ] Write wiki page proposal of first experiment
 - [ ] Write a wiki page report of initial small scale prototype results

**Comment by hjmjohnson** [comment]
```bash
cat requirements.txt
alabaster==0.7.12
appdirs==1.4.3
appnope==0.1.0
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
bids-validator==1.2.3
black==19.3b0
bleach==3.1.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
docopt==0.6.2
docutils==0.14
entrypoints==0.3
idna==2.8
imagesize==1.1.0
ipydatawidgets==4.0.0
ipykernel==5.1.0
ipympl==0.2.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
itk==5.0rc1
itk-core==5.0rc2
itk-filtering==5.0rc2
itk-io==5.0rc2
itk-numerics==5.0rc2
itk-registration==5.0rc2
itk-segmentation==5.0rc2
itkwidgets==0.16.1
jedi==0.13.3
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.6
jupyterlab-server==0.2.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.0.3
mistune==0.8.4
nbconvert==5.5.0
nbformat==4.4.0
nibabel==2.4.0
notebook==5.7.8
num2words==0.5.9
numpy==1.16.3
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.4.0
patsy==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
prometheus-client==0.6.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pybids==0.8.0+77.g30d924c
Pygments==2.3.1
pyparsing==2.4.0
pyrsistent==0.15.1
python-dateutil==2.8.0
pytz==2019.1
pyzmq==18.0.1
requests==2.21.0
scikit-learn==0.20.3
scipy==1.2.1
Send2Trash==1.5.0
SimpleITK==1.2.0
six==1.12.0
snowballstemmer==1.2.1
Sphinx==2.0.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
terminado==0.8.2
testpath==0.4.2
toml==0.10.0
tornado==6.0.2
traitlets==4.3.2
traittypes==0.2.1
urllib3==1.24.3
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
zstandard==0.11.0
```

```python
def read_fiducial_points(fcsv_file: str, fiducials:list) -> dict:
    col_names="id,x,y,z,ow,ox,oy,oz,vis,sel,lock,label,desc,associatedNodeID"
    with open(fcsv_file, 'r') as fid: 
        df = pd.read_csv(fid, sep=',', comment='#', names=col_names.split(',')) 

    fid_pts = {}
    for fid in fiducials:
        fid_pts[fid] = df[ df['label'] == fid].iloc[0][1:4].values
        # flip RAS fiducials to be LPS
        fid_pts[fid][0] = -1*fid_pts[fid][0]
        fid_pts[fid][1] = -1*fid_pts[fid][1]
    return fid_pts
```
