### ISSUE TITLE
Learn ITK python interface

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#31]
# User Story

As an `Algorithm developer`,
I want `to efficiently process medical images`
so that `deep learning algorithms can be prototyped quickly.`

## Detailed Description
Learn how to use the ITK python interfaces

### Tasks to be completed 

 - [x] Review and be familiar with https://github.com/KitwareMedical/2019-03-13-KRSCourseInBiomedicalImageAnalysisAndVisualization

### Acceptance Criteria
 - [x] Can read in images in ITK
 - [x] Can identify nearest index location of landmark points
 - [x] Can convert index locations to physical points

**Comment by ArjitJ** [comment]
Attempts to load "_RE_LE.nii.gz" files using itk.imread() result in Segmentation fault. A workaround to this is by using sitk.ReadImage() to read these files.
