### ISSUE TITLE
BIDS Filename Generation

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#34]
# User Story
As `DataCurator`,
I want `write BrainsAutoWorkup output files to disk in the BIDS naming convention`
so that `the output of BAW is a valid BIDS dataset`

### Tasks to be completed 

 - [x] Create a generic class for generating BIDS compliant filenames
 - [ ] Integrate BIDS naming into `singleSession.py` and `template.py`

### Acceptance Criteria
 - [ ] BAW `singleSession` and `template` outputs have valid BIDS file names (validated using [pybids](https://github.com/bids-standard/pybids))
 - [ ] All breaking changes remedied

**Comment by abpwrs** [comment]
In reference to task:    
> Integrate BIDS naming into `singleSession.py` and `template.py` .    
  
I have modified the hardcoded file names that made sense to me.     
Relevant commits:     
[template.py](https://github.com/BRAINSia/BRAINSTools/commit/74e9c225f92662f7e3f065d171a9c1e92a8ebc66#diff-80c0a81a46e1ef2a76e8d09b15b4f8a5)
[singleSession.py](https://github.com/BRAINSia/BRAINSTools/commit/ff68040031256a29da568b65474148b20e79545a#diff-80c0a81a46e1ef2a76e8d09b15b4f8a5)           
  
   
@hjmjohnson Is there any way that I can mock up the output of BAW to test?

**Comment by hjmjohnson** [comment]
@abpwrs I don't know of a quick way to do that.  Can you make a PR of this so that I can test the PR?  Make the PR a WIP so that it is clear that it is not to be merged at the moment.
