### ISSUE TITLE
Create several defaced variants of images

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#35]
# User Story
As a `data curator`,
I want `to deface images with various algorithms`
so that `we can build robust algorithms for defaced data.`

### Tasks to be completed 

 - [x] Deface with a variant of "https://github.com/BRAINSia/BIDSonym" "run.py" that does not require bids data structure.  create "pydeface", "mri_deface", "deface_wf", "mridefacer" variants of each image.
 - [x] Deface with https://nrg.wustl.edu/software/face-masking/ (https://hub.docker.com/r/mohanar/facemasking/tags)
 - [ ] Train for landmark finding (including eye finding) even when eyes are removed by defacer.

### Acceptance Criteria
 - [x] A complete set of defaced images are created

**Comment by ArjitJ** [comment]
https://github.com/ArjitJ/BIDSonym

The files are in files.txt, the run script takes in one argument(path of the image)

**Comment by ArjitJ** [comment]
The nrg defacing outputs are not properly aligned with the inputs. (Do not overlap in slicer). Need to perform registration before using in the dataset
