### ISSUE TITLE
Generalize Image Augmentation Script

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#4]
## User Story

As an AlgorithmDev,
I want to easily augment a dataset of images via rotations and axis-flipping 
so that I can develop more robust models with less data.     

## Detailed Description

The current script for augmenting 2D Images loads every image in the dataset into RAM, and then performs the augmentation, and then writes all images back. This clearly limits the size of the dataset that can be augmented. This feature will alter the existing framework to work on one image at a time, which can then be run on all images using BASH scripting.

### Tasks to be completed 

 - [x] Alter existing code to work on a single image at a time
 - [x] Write a generic BASH script so that this program can be applied to all images
 - [x] Ensure that the script is generic enough to work on any dataset

### Acceptance Criteria

 - [x] Script must work on any size of dataset (more than could fit in RAM at any single point in time)
 - [x] Script must provide a generic interface so that it can be reused on any project
 - [x] Script must have generic I/O, FileType, and Augmentation parameters
