### ISSUE TITLE
Resize label maps to the same voxel size as images

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#6]
# User Story
As an AlgorithmDev,
I want to resize label-maps to be the same size as the images,
so that we can easily convert to numpy arrays for DL.

## Detailed Description

The script should take in one label map and one image and return a resized label that is still in the correct physical space, but with the correct number of voxels so that the numpy arrays mach in shape. Current script loads everything into RAM and the transforms labels.

### Tasks to be completed 

 - [x] Alter existing code to work on a single image at a time
 - [x] Write a generic BASH script so that this program can be applied to all images
 - [x] Ensure that the script is generic enough to work on any data-set
 - [x] Resizing must work on N-dimensional data

### Acceptance Criteria
 - [x]  Script must work on any size of data-set (more than could fit in RAM at any single point in time)
 - [x] Script must work on N-dimensional data
 - [x] Script must have generic I/O parameters
