### ISSUE TITLE
Image Visualization Notebooks

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#7]
# User Story

As an AlgorithmDev,
I want quickly visualize my data,
so that I can check the outputs of me algorithm.

## Detailed Description

This feature is a set of Jupyter Notebooks for rapid visualization of 2D and 3D images using matplotlib for visualization and iPython Widgets for interactivity.

### Tasks to be completed 

 - [ ] Notebook for visualizing slices of a 3D image w/ a slider iPython Widget to change slice
 - [ ] Batch visualization of 2D images and 3D slices

### Acceptance Criteria
 - [ ] Notebooks must be easily altered to work on different data sets (just changing a CONST at the top of the file)
 - [ ] Notebooks should work in both Jupyter Notebooks and Jupyter Labs
 - [ ] Notebooks must have compatibility up to at least 3D
 - [ ] Notebooks must be interactive for 3D so that you can view different slices across any axis

**Comment by abpwrs** [comment]
This idea is already implemented with [itk-widgets](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets). Closing issue.
